-- DOMAINS TO FIREBIRD

CREATE DOMAIN D_INVOICE CHAR(9); 
 
CREATE DOMAIN D_CNPJ AS VARCHAR(14);

CREATE DOMAIN D_GOVID AS VARCHAR(11);


CREATE DOMAIN D_DATE AS TIMESTAMP;

CREATE DOMAIN D_DECIMAL AS NUMERIC(15,2);

CREATE DOMAIN D_FINALIZED AS CHAR(1);

CREATE DOMAIN D_INT AS INTEGER;

CREATE DOMAIN D_PK AS INTEGER NOT NULL;

CREATE DOMAIN D_STR020 AS VARCHAR(20);

--SOCIAL REASON
CREATE DOMAIN D_SR AS VARCHAR(60);

CREATE DOMAIN D_NAME AS VARCHAR(100);

CREATE DOMAIN TELEPHONE AS VARCHAR(20);

CREATE DOMAIN FANTASY_NAME AS VARCHAR(100);

CREATE DOMAIN D_INVOICE AS CHAR(9)

CREATE DOMAIN D_EMAIL AS varchar(100) NOT NULL;

CREATE DOMAIN D_UNIT AS VARCHAR(20) NOT NULL;

CREATE DOMAIN D_USERNAME CHAR(40);

CREATE DOMAIN D_PASSWORD CHAR(40);

CREATE DOMAIN D_ACESSO char(13);

CREATE DOMAIN D_USERTYPE CHAR(15);
