/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automatocelulartempo;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class View extends javax.swing.JFrame {    
    Matrix mat;
    public int cont_dias;
    private MatrixImagePanel matrixpanel;  
    public int dim;
    public Timer t;
    /**
     * Creates new form gameofLife
     */
    public View() {
        this.setTitle("Game of Life");
        initComponents();
        
        cont_dias = 0;        
     
//        int dim = Integer.parseInt(JOptionPane.showInputDialog(null,
//                "Insira a dimensao da matriz"));        
        dim = 42;
        mat = new Matrix(dim,dim, this);       
        
        
                        
        
        layerpanel.remove(mapars);
    
        DesenhaMatriz(dim,dim);
        layerpanel.add(mapars);
        
        //legenda sol
        estadoSol.setBackground(new Color(1f,1f,0f,0.4f));
        estadoChuva.setBackground(new Color(0f,0f,1f,0.35f));
        estadoNublado.setBackground(new Color(0.7f,0.7f,0.7f,0.5f));      
        new Timer(this);                
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        rulesPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        estadoSol = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        estadoChuva = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        estadoNublado = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        layerpanel = new javax.swing.JLayeredPane();
        mapars = new javax.swing.JLabel();
        contGeracaoLabel = new javax.swing.JLabel();
        newGenerationButton = new javax.swing.JToggleButton();

        jMenuItem1.setText("jMenuItem1");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));

        jLabel2.setText("Se o estado for nublado e tiver 4 ou mais vizinhos nublados, muda para chuva.");

        jLabel1.setText("Se o estado for Sol e tiver 4 ou mais vizinhos nublados,  muda para nublado.");

        jLabel4.setText("Se o estado for Sol e tiver 5 ou mais vizinhos com chuva, muda para chuva.");

        jLabel6.setText("Regras de Vizinhança");

        jLabel3.setText("Regras");

        jLabel7.setText("Regras de contagem de dias");

        jLabel8.setText("Se o estado for nublado por mais de um dia, o tempo muda para chuva.");

        jLabel9.setText("Se o estado for Sol por mais de 2 dias, ele vira nublado.");

        jLabel10.setText("Se o estado for chuva, no próximo dia será Sol.");

        estadoSol.setToolTipText("");

        javax.swing.GroupLayout estadoSolLayout = new javax.swing.GroupLayout(estadoSol);
        estadoSol.setLayout(estadoSolLayout);
        estadoSolLayout.setHorizontalGroup(
            estadoSolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );
        estadoSolLayout.setVerticalGroup(
            estadoSolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 89, Short.MAX_VALUE)
        );

        jLabel5.setText("Sol");

        estadoChuva.setToolTipText("");

        javax.swing.GroupLayout estadoChuvaLayout = new javax.swing.GroupLayout(estadoChuva);
        estadoChuva.setLayout(estadoChuvaLayout);
        estadoChuvaLayout.setHorizontalGroup(
            estadoChuvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 89, Short.MAX_VALUE)
        );
        estadoChuvaLayout.setVerticalGroup(
            estadoChuvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel11.setText("Chuva");

        estadoNublado.setToolTipText("");

        javax.swing.GroupLayout estadoNubladoLayout = new javax.swing.GroupLayout(estadoNublado);
        estadoNublado.setLayout(estadoNubladoLayout);
        estadoNubladoLayout.setHorizontalGroup(
            estadoNubladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );
        estadoNubladoLayout.setVerticalGroup(
            estadoNubladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 89, Short.MAX_VALUE)
        );

        jLabel12.setText("Nublado");

        javax.swing.GroupLayout rulesPanelLayout = new javax.swing.GroupLayout(rulesPanel);
        rulesPanel.setLayout(rulesPanelLayout);
        rulesPanelLayout.setHorizontalGroup(
            rulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rulesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rulesPanelLayout.createSequentialGroup()
                        .addGroup(rulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rulesPanelLayout.createSequentialGroup()
                                .addGap(0, 10, Short.MAX_VALUE)
                                .addGroup(rulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)))
                            .addGroup(rulesPanelLayout.createSequentialGroup()
                                .addGroup(rulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(rulesPanelLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(rulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(rulesPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(estadoSol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(rulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estadoNublado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(14, 14, 14)
                        .addGroup(rulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(estadoChuva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        rulesPanelLayout.setVerticalGroup(
            rulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rulesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(7, 7, 7)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(rulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(rulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(estadoChuva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estadoNublado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estadoSol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(92, 92, 92))
        );

        layerpanel.setBackground(new java.awt.Color(215, 220, 225));
        layerpanel.setForeground(new java.awt.Color(220, 220, 220));

        mapars.setIcon(new javax.swing.ImageIcon("/home/vinipachecov/Repos/Unifra/2017/ModelagemSimulacao/maparsBW.png")); // NOI18N

        layerpanel.setLayer(mapars, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layerpanelLayout = new javax.swing.GroupLayout(layerpanel);
        layerpanel.setLayout(layerpanelLayout);
        layerpanelLayout.setHorizontalGroup(
            layerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(layerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layerpanelLayout.createSequentialGroup()
                    .addComponent(mapars, javax.swing.GroupLayout.PREFERRED_SIZE, 928, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 20, Short.MAX_VALUE)))
        );
        layerpanelLayout.setVerticalGroup(
            layerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 769, Short.MAX_VALUE)
            .addGroup(layerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layerpanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mapars, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        contGeracaoLabel.setText("Dia");

        newGenerationButton.setText("Próximo Dia");
        newGenerationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newGenerationButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(layerpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(rulesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(contGeracaoLabel)
                        .addGap(43, 43, 43)
                        .addComponent(newGenerationButton)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(layerpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rulesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contGeracaoLabel)
                    .addComponent(newGenerationButton))
                .addGap(191, 191, 191))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newGenerationButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGenerationButtonMouseClicked
        // TODO add your handling code here:
        //        
        //update matrix (remove older to replace for the newer)
      this.mat.newGeneration();            
      this.newGenerationButton.setSelected(false);


      this.repaint();        
      contGeracaoLabel.setText(++cont_dias +"° Dia" );
        
        
    }//GEN-LAST:event_newGenerationButtonMouseClicked

    /**
     * @param args the command line arguments
     */

    public void mudaGeracao(){
        this.mat.newGeneration();            
      this.newGenerationButton.setSelected(false);      
       this.repaint();        
        contGeracaoLabel.setText(++cont_dias +"° Dia" );
    }
    

    public void removeMatrix(){
        for (int k = 0; k < mat.getLins(); k++) {
            for (int l = 0; l < mat.getCols(); l++) {                
                layerpanel.removeAll();
            }                
        }     
    }
//    
    public void DesenhaMatriz(int lins, int cols){        

        for (int i = 0; i < lins; i++) {
            for (int j = 0; j < cols; j++) {                                
                layerpanel.add(mat.getCell(i, j), 2);                
            }            
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contGeracaoLabel;
    private javax.swing.JPanel estadoChuva;
    private javax.swing.JPanel estadoNublado;
    private javax.swing.JPanel estadoSol;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLayeredPane layerpanel;
    private javax.swing.JLabel mapars;
    private javax.swing.JToggleButton newGenerationButton;
    private javax.swing.JPanel rulesPanel;
    // End of variables declaration//GEN-END:variables
}
