/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula30marco;

import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class gameofLife extends javax.swing.JFrame {    
    Automaton [][]mat2;
    Matrix mat;
    public int cont_geracao;
    
    /**
     * Creates new form gameofLife
     */
    public gameofLife() {
        this.setTitle("Game of Life");
        initComponents();
        
        cont_geracao = 0;
        contGeracaoLabel.setText("Geração: " + cont_geracao);
     
        int dim = Integer.parseInt(JOptionPane.showInputDialog(null,
                "Insira a dimensao da matriz"));        
        int linhaviva = Integer.parseInt(JOptionPane.showInputDialog(null,
                "Insira o número da linha que estara viva"));        
        mat2 = new Automaton[dim][dim];
        mat = new Matrix(dim,dim, this);
        mat.patternMatrix(linhaviva);
        DesenhaMatriz(4,4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        contGeracaoLabel = new javax.swing.JLabel();
        newGenerationButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jLabel1.setText("Se uma célula tiver um vizinho vivo, ela nasce ou segue viva.");

        jLabel2.setText("Se uma célula não tiver vizinhos vivos, ela morre.");

        jLabel3.setText("Regras");

        jLabel4.setText("Se uma célula tiver dois vizinho vivo, ela nasce ou segue viva.");

        jLabel5.setText("S.e uma célula tiver dois ou mais vizinhos vivo, ela morre por superpopulação");

        contGeracaoLabel.setText("Geração");

        newGenerationButton.setText("Nova Geração");
        newGenerationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newGenerationButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(contGeracaoLabel)
                        .addGap(27, 27, 27)
                        .addComponent(newGenerationButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(contGeracaoLabel)
                        .addComponent(newGenerationButton)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newGenerationButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGenerationButtonMouseClicked
        // TODO add your handling code here:
        //        
        //update matrix (remove older to replace for the newer)
        newGeneration();
    }//GEN-LAST:event_newGenerationButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    
    public void newGeneration(){
          if(mat != null){
            for (int i = 0; i < mat.getLins(); i++) {
                for (int j = 0; j < mat.getCols(); j++) {
                    this.remove(mat.getCell(i, j));
                }                
            }
        }        
        mat = mat.newGenaration();
        DesenhaMatriz(mat.getLins(), mat.getCols());
        newGenerationButton.setSelected(false);
        cont_geracao++;
        contGeracaoLabel.setText("Geração: " + cont_geracao);        
    }
    
     public void newGenerationInserted(Automaton different){
        if(different.getState()) {
            if(mat != null){              
              for (int i = 0; i < mat.getLins(); i++) {
                  for (int j = 0; j < mat.getCols(); j++) {
                      this.remove(mat.getCell(i, j));                        
                    }                
                }
            }                    
        }else{
            int lin = different.getLin();
            int col = different.getCol();
            mat.mat[lin][col] = new Automaton(lin,col,!different.getState(),this);
        }
          
        mat = mat.newGenaration();
        DesenhaMatriz(mat.getLins(), mat.getCols());
        newGenerationButton.setSelected(false);
        cont_geracao++;
        contGeracaoLabel.setText("Geração: " + cont_geracao);        
    }
    
    public void DesenhaMatriz(int lins, int cols){        
        // blocos de 40x40                
        for (int i = 0; i < lins; i++) {
            for (int j = 0; j < cols; j++) {                
                this.add(mat.getCell(i, j));
            }            
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gameofLife.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gameofLife.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gameofLife.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gameofLife.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gameofLife().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contGeracaoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton newGenerationButton;
    // End of variables declaration//GEN-END:variables
}
