/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula30marco;

import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class gameofLife extends javax.swing.JFrame {    
    Matrix mat;
    public int cont_geracao;
    
    /**
     * Creates new form gameofLife
     */
    public gameofLife() {
        this.setTitle("Game of Life");
        initComponents();
        
        cont_geracao = 0;
        contGeracaoLabel.setText("Geração: " + cont_geracao);
     
        int dim = Integer.parseInt(JOptionPane.showInputDialog(null,
                "Insira a dimensao da matriz"));        
//        int linhaviva = Integer.parseInt(JOptionPane.showInputDialog(null,
//                "Insira o número da linha que estara viva"));            
        mat = new Matrix(dim,dim, this);
        //mat.patternMatrix(linhaviva);
        DesenhaMatriz(dim,dim);
        System.out.println("MATRIZ ANTES");
        mat.printStates();
        newGenerationButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        contGeracaoLabel = new javax.swing.JLabel();
        newGenerationButton = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Se uma célula tiver um vizinho vivo, ela nasce ou segue viva.");

        jLabel2.setText("Se uma célula não tiver vizinhos vivos, ela mantêm o estado.");

        jLabel3.setText("Regras");

        jLabel4.setText("Se uma célula tiver dois vizinho vivo, ela nasce ou segue viva.");

        jLabel5.setText("S.e uma célula tiver dois ou mais vizinhos vivo, ela morre por superpopulação");

        contGeracaoLabel.setText("Geração");

        newGenerationButton.setText("Nova Geração");
        newGenerationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newGenerationButtonMouseClicked(evt);
            }
        });

        jButton1.setText("Configurar Matriz");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(contGeracaoLabel)
                        .addGap(27, 27, 27)
                        .addComponent(newGenerationButton)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contGeracaoLabel)
                    .addComponent(newGenerationButton)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newGenerationButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGenerationButtonMouseClicked
        // TODO add your handling code here:
        //        
        //update matrix (remove older to replace for the newer)
        newGeneration();
    }//GEN-LAST:event_newGenerationButtonMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        ConfigMatrix configmat = new ConfigMatrix(mat.getLins(),this);
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    
    public void setMatrix(Matrix newMat){
        removeMatrix();   
        mat = newMat;
        newGenerationButton.setEnabled(true);
        //disableClick();             
        DesenhaMatriz(mat.getLins(), mat.getCols());
        mat.printStates();
    }
    
    public void disableClick(){
        for (int i = 0; i < mat.getLins(); i++) {
            for (int j = 0; j < mat.getCols(); j++) {
                mat.mat[i][j].setEnabled(false);
            }            
        }
    }
    
    public void newGeneration(){
          if(mat != null){
            for (int i = 0; i < mat.getLins(); i++) {
                for (int j = 0; j < mat.getCols(); j++) {
                    this.remove(mat.getCell(i, j));
                }                
            }
        }        
        mat = mat.newGeneration(this);
        DesenhaMatriz(mat.getLins(), mat.getCols());
        newGenerationButton.setSelected(false);
        cont_geracao++;
        contGeracaoLabel.setText("Geração: " + cont_geracao);        
    }
    
     public void newGenerationInserted(int i , int j){
         
         
        //remove cells from GUI
        for (int k = 0; k < mat.getLins(); k++) {
            for (int l = 0; l < mat.getCols(); l++) {                
                this.remove(mat.getCell(k, l));                        
            }                
        }
//
//        //check if clicked block has to change it's state
//        // if it's alive keep alive
//        // if it's dead switch to FrankenAlive         
//        
        if(!mat.mat[i][j].getState()){
            System.out.println("Modificou o i = " + i + " j = " + j );
            mat.mat[i][j] = new Automaton(i,j,!mat.mat[i][j].getState(),this);
            System.out.println("Nova matriz com o automato clicado alterado");    
            mat.printStates();
        }
        
        
            
        mat = mat.newGeneration(this);
                
        DesenhaMatriz(mat.getLins(), mat.getCols());
        this.repaint();
        newGenerationButton.setSelected(false);
        cont_geracao++;
        contGeracaoLabel.setText("Geração: " + cont_geracao);        
    }
     
    public void removeMatrix(){
        for (int k = 0; k < mat.getLins(); k++) {
            for (int l = 0; l < mat.getCols(); l++) {                
                this.remove(mat.getCell(k, l));                        
            }                
        }     
    }
    
    public void DesenhaMatriz(int lins, int cols){        
        // blocos de 40x40                
        for (int i = 0; i < lins; i++) {
            for (int j = 0; j < cols; j++) {                
                this.add(mat.getCell(i, j));
            }            
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gameofLife.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gameofLife.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gameofLife.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gameofLife.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gameofLife().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contGeracaoLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JToggleButton newGenerationButton;
    // End of variables declaration//GEN-END:variables
}
