/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula30marco;

/**
 *
 * @author root
 */
public class ConfigMatrix extends javax.swing.JFrame {
    Matrix mat;
    gameofLife view;
    /**
     * Creates new form ConfigMatrix
     */
    
    public ConfigMatrix(int dim, gameofLife view) {
        
        initComponents();
        this.setTitle("Configurar Matriz do Inicial");        
        mat = new Matrix(dim,dim, view,this);
        this.view = view;
        DesenhaMatrix(dim,dim);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newMatrixbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newMatrixbutton.setText("Retornar Matriz");
        newMatrixbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMatrixbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newMatrixbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(316, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(366, Short.MAX_VALUE)
                .addComponent(newMatrixbutton)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newMatrixbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMatrixbuttonActionPerformed
        // TODO add your handling code here:
        view.setMatrix(mat);
        this.setVisible(false);
    }//GEN-LAST:event_newMatrixbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void updateMatrix(){
        for (int i = 0; i < mat.getLins(); i++) {
            for (int j = 0; j < mat.getCols(); j++) {
                this.remove(mat.getCell(i, j));
            }            
        }        
        DesenhaMatrix(mat.getLins(), mat.getCols());
    }
    
    public void DesenhaMatrix(int lins, int cols){        
        // blocos de 40x40                
        for (int i = 0; i < lins; i++) {
            for (int j = 0; j < cols; j++) {                
                this.add(mat.getCell(i, j));
            }            
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton newMatrixbutton;
    // End of variables declaration//GEN-END:variables
}
