-- 2 ATIVIDADE 6



--1 - Fazer uma stored procedure que receba como parâmetro de entrada um período, calcule o total (R$) em produtos vendidos no período e mostre:
--- Nome do Produto,
--- Total (R$) do produto,
--- Percentual de venda do produto em relação ao total vendido no período.

CREATE or alter PROCEDURE SPPRODVEND (D1 DATE, D2 DATE)
RETURNS (NOMEP D_NOME, TOTAL D_DECIMAL, PERCENTV D_DECIMAL, totalacum D_DECIMAL, PERCACUM D_DECIMAL)
AS
	DECLARE VARIABLE TOTALVENDAS D_DECIMAL;
BEGIN	
	
	SELECT SUM(iV.VALORUNITARIO*iv.QUANTIDADE) 
    FROM ITEMVENDA iV 
    INNER JOIN VENDA v ON iv.CODVENDA=v.CODIGO
    WHERE V.DATAVENDA BETWEEN :D1 AND :D2
    INTO :TOTALVENDAS;
    
    TOTALACUM=0;
    PERCACUM=0;
	
    if (:totalvendas >0) then
    begin
	  FOR SELECT DISTINCT P.NOME, SUM(iV.VALORUNITARIO*iv.QUANTIDADE)
		FROM ITEMVENDA IV
		iNNER JOIN VENDA V ON IV.CODVENDA = V.CODIGO
		INNER JOIN produto p ON iv.CODPRODUTO=p.CODIGO
		WHERE V.DATAVENDA BETWEEN :D1 AND :D2
		GROUP BY p.NOME 
   		INTO :NOMEP, :TOTAL   
      DO BEGIN	   
	     PERCENTV=(:TOTAL*100)/:TOTALVENDAS;
	     TOTALACUM=:TOTALACUM+:TOTAL;
	     PERCACUM=:PERCACUM+:PERCENTV;	   
	     SUSPEND;
     END
   end
END 





--2 - Fazer uma stored procedure que receba como parâmetro de entrada um período, calcule o total (R$) em produtos vendidos e comprados no período e mostre:
--- Nome do Produto,
--- Total (R$) vendido do produto,
--- Percentual de venda do produto em relação ao total vendido no período.
--- Total (R$) comprado do produto,
--- Percentual de compra do produto em relação ao total comprado no período.

EXECUTE PROCEDURE SP_PROD_VEND_COMP('2017-01-01', '2017-09-09');


CREATE OR ALTER PROCEDURE SP_PROD_VEND_COMP (D1 DATE, D2 DATE)
RETURNS (NOMEP VARCHAR(60), TOTALVENDAS D_DECIMAL, PERCENTV D_DECIMAL, TOTALCOMPRAS D_DECIMAL, PERCENTC D_DECIMAL)
AS
	DECLARE VARIABLE IDPRODUTO INT;
	DECLARE VARIABLE TOTALVENDAS D_DECIMAL;
	DECLARE VARIABLE TOTALCOMPRAS D_DECIMAL;
BEGIN
	
	SELECT SUM(iV.VALORUNITARIO*iv.QUANTIDADE) 
    FROM ITEMVENDA iV 
    INNER JOIN VENDA v ON iv.CODVENDA=v.CODIGO
    WHERE V.DATAVENDA BETWEEN :D1 AND :D2
    INTO :TOTALVENDAS;
	
    SELECT SUM(IC.VALORUNITARIO * IC.QUANTIDADE)
    FROM ITEMCOMPRA IC
	INNER JOIN COMPRA C ON IC.CODCOMPRA = C.CODIGO
	WHERE C.DATACOMPRA BETWEEN :D1 AND :D2
	INTO :TOTALCOMPRAS;

	IF ((:TOTALVENDAS > 0) OR (:TOTALCOMPRAS > 0))THEN
	BEGIN
		FOR SELECT DISTINCT P.CODIGO, P.NOME
		FROM PRODUTO P
		WHERE EXISTS (SELECT IV.CODPRODUTO
					 FROM ITEMVENDA IV
					 INNER JOIN VENDA V ON IV.CODVENDA = V.CODIGO
					 WHERE V.DATAVENDA BETWEEN :D1 AND :D2 AND IV.CODPRODUTO = P.CODIGO) OR EXISTS (
					 																			SELECT IC.CODPRODUTO 
					 																			FROM  ITEMCOMPRA IC
					 																			INNER JOIN COMPRA C ON IC.CODCOMPRA = C.CODIGO
					 																			WHERE  C.DATACOMPRA BETWEEN :D1 AND :D2 AND IC.CODPRODUTO = P.CODIGO)
	   INTO :IDPRODUTO, :NOMEP
	   DO BEGIN
		   
		  
		   SUSPEND;
	   END 
   END
END



CREATE OR ALTER PROCEDURE SP_CALCP2_CV (D1 DATE, D2 DATE)
RETURNS (NOMEP VARCHAR(60), TOTALVENDAS D_DECIMAL, PERCENTV D_DECIMAL, TOTALCOMPRAS D_DECIMAL, PERCENTC D_DECIMAL)
AS
	DECLARE VARIABLE IDPRODUTO D_INTEIRO;
	DECLARE VARIABLE TOTALVP D_DECIMAL;
	DECLARE VARIABLE TOTALCP D_DECIMAL;
BEGIN
	
	SELECT SUM(iV.VALORUNITARIO*iv.QUANTIDADE) 
    FROM ITEMVENDA iV 
    INNER JOIN VENDA v ON iv.CODVENDA=v.CODIGO
    WHERE V.DATAVENDA BETWEEN :D1 AND :D2
    INTO :TOTALVP;
	
    SELECT SUM(IC.VALORUNITARIO * IC.QUANTIDADE)
    FROM ITEMCOMPRA IC
	INNER JOIN COMPRA C ON IC.CODCOMPRA = C.CODIGO
	WHERE C.DATACOMPRA BETWEEN :D1 AND :D2
	INTO :TOTALCP;

	--IF ((:TOTALVP > 0) OR (:TOTALCP > 0))THEN
	--BEGIN
		FOR SELECT DISTINCT P.CODIGO, P.NOME
		FROM PRODUTO P
		WHERE P.CODIGO IN (SELECT DISTINCT IV.CODPRODUTO
					 FROM ITEMVENDA IV
					 INNER JOIN VENDA V ON IV.CODVENDA = V.CODIGO
					 WHERE V.DATAVENDA BETWEEN :D1 AND :D2 AND IV.CODPRODUTO = P.CODIGO) 
		OR P.CODIGO IN (SELECT DISTINCT IC.CODPRODUTO 
		 			 FROM  ITEMCOMPRA IC
				     INNER JOIN COMPRA C ON IC.CODCOMPRA = C.CODIGO
 					 WHERE  C.DATACOMPRA BETWEEN :D1 AND :D2 AND IC.CODPRODUTO = P.CODIGO)
	   ORDER BY P.NOME
	   INTO :IDPRODUTO, :NOMEP
	   DO BEGIN
		   SELECT SUM(IV.QUANTIDADE * IV.VALORUNITARIO)
		   FROM ITEMVENDA IV
		   INNER JOIN VENDA V ON IV.CODVENDA = V.CODIGO
		   WHERE V.DATAVENDA BETWEEN :D1 AND :D2 AND IV.CODPRODUTO = :IDPRODUTO
		   INTO :TOTALVENDAS;
		   
		   SELECT SUM(IC.QUANTIDADE * ic.VALORUNITARIO)
		   FROM ITEMCOMPRA IC
		   INNER JOIN COMPRA C ON IC.CODCOMPRA = C.CODIGO
		   WHERE C.DATACOMPRA BETWEEN  :D1 AND :D2 AND IC.CODPRODUTO = :IDPRODUTO
		   INTO :TOTALCOMPRAS;
		   
		   PERCENTV = (:TOTALVENDAS * 100) / :TOTALVP;
		   PERCENTC = (:TOTALCOMPRAS * 100 ) / :TOTALCP;		   
     	   SUSPEND;
	   --END 
   END
END 










---------------------------------------------


CREATE PROCEDURE SP_BUSCA_PROD( D1 D_DATA, D2 D_DATA)
RETURNS (
	IDP D_INTEIRO, NOMEPROD D_NOME
)
AS 
BEGIN
	FOR SELECT DISTINCT IV.CODPRODUTO, P.NOME
	FROM ITEMVENDA IV
	INNER JOIN VENDA V ON IV.CODVENDA = V.CODIGO
	INNER JOIN PRODUTO P ON IV.CODPRODUTO = P.CODIGO
	WHERE V.DATAVENDA BETWEEN :D1 AND :D2
	UNION
	SELECT DISTINCT IC.CODPRODUTO, P.NOME
	FROM ITEMCOMPRA IC
	INNER JOIN COMPRA C ON IC.CODCOMPRA = C.CODIGO
	INNER JOIN PRODUTO P  ON ic.CODPRODUTO = P.CODIGO
	WHERE C.DATACOMPRA BETWEEN :D1 AND :D2
	INTO :IDP, NOMEPROD
	DO BEGIN
		SUSPEND;
	END 
END 



SELECT DISTINCT * 
FROM SP_BUSCA_PROD('2017-01-01', '2017-09-09')


SELECT * FROM VENDA;

SELECT * FROM SP_CALCP2_CV('2017-01-01', '2017-09-09')

SELECT * FROM SP_CALCP_CV('2017-01-01', '2017-09-09')


CREATE OR ALTER PROCEDURE SP_CALCP_CV (D1 D_DATA, D2 D_DATA)
RETURNS( NOMEPRODUTO D_NOME, VALORVENDA D_DECIMAL, PERCVENDA D_DECIMAL, VALORCOMPRA D_DECIMAL, PERCCOMPRA D_DECIMAL)
AS
	DECLARE VARIABLE IDPROD D_INTEIRO;
	DECLARE VARIABLE TOTALVENDA D_DECIMAL;
	DECLARE VARIABLE TOTALCOMPRA D_DECIMAL;	
BEGIN
	
	SELECT SUM(IV.QUANTIDADE * IV.VALORUNITARIO)
	FROM ITEMVENDA IV
	INNER JOIN VENDA V ON IV.CODVENDA = V.CODIGO 
	WHERE V.DATAVENDA BETWEEN :D1 AND :D2
	INTO :TOTALVENDA;
	
	SELECT SUM(IC.QUANTIDADE * IC.VALORUNITARIO)
	FROM ITEMCOMPRA IC
	INNER JOIN COMPRA C ON IC.CODCOMPRA = C.CODIGO
	WHERE C.DATACOMPRA BETWEEN :D1 AND :D2
	INTO :TOTALCOMPRA;
	
	FOR SELECT DISTINCT S.IDP, S.NOMEPROD 
	FROM SP_BUSCA_PROD(:D1, :D2) S
	ORDER BY S.NOMEPROD
	INTO :IDPROD, :NOMEPRODUTO
	DO BEGIN
		SELECT SUM(IV.QUANTIDADE * IV.VALORUNITARIO)
		FROM ITEMVENDA IV
		INNER JOIN VENDA V ON IV.CODVENDA = V.CODIGO
		WHERE V.DATAVENDA BETWEEN :D1 AND :D2 AND IV.CODPRODUTO = :IDPROD
		INTO :VALORVENDA;
		
		SELECT SUM(IC.QUANTIDADE * IC.VALORUNITARIO)
		FROM ITEMCOMPRA IC
		INNER JOIN COMPRA C ON IC.CODCOMPRA = C.CODIGO 
		WHERE C.DATACOMPRA BETWEEN :D1 AND :D2 AND IC.CODPRODUTO = :IDPROD
		INTO :VALORCOMPRA;
		
		PERCVENDA = (:VALORVENDA * 100) / :TOTALVENDA;
		PERCCOMPRA = (:VALORCOMPRA * 100 ) / :TOTALCOMPRA;
		SUSPEND;
	END
END 