--Elabore índices que possam auxiliar no ganho de desempenho de no mínimo 5 consultas complexas
-- (utilize joins, agrupamentos e aninhamentos)


-- SP 

SELECT * FROM SP_CALCP_CV('2017-01-01', '2017-09-09')

-- media de 5ms e 13ms

-- indice

CREATE unique INDEX IDX_NOMEPROD ON PRODUTO(NOME);


CREATE OR ALTER PROCEDURE SP_CALCP_CV (D1 D_DATA, D2 D_DATA)
RETURNS( NOMEPRODUTO D_NOME, VALORVENDA D_DECIMAL, PERCVENDA D_DECIMAL, VALORCOMPRA D_DECIMAL, PERCCOMPRA D_DECIMAL)
AS
	DECLARE VARIABLE IDPROD D_INTEIRO;
	DECLARE VARIABLE TOTALVENDA D_DECIMAL;
	DECLARE VARIABLE TOTALCOMPRA D_DECIMAL;	
BEGIN
	
	SELECT SUM(IV.QUANTIDADE * IV.VALORUNITARIO)
	FROM ITEMVENDA IV
	INNER JOIN VENDA V ON IV.CODVENDA = V.CODIGO 
	WHERE V.DATAVENDA BETWEEN :D1 AND :D2
	INTO :TOTALVENDA;
	
	SELECT SUM(IC.QUANTIDADE * IC.VALORUNITARIO)
	FROM ITEMCOMPRA IC
	INNER JOIN COMPRA C ON IC.CODCOMPRA = C.CODIGO
	WHERE C.DATACOMPRA BETWEEN :D1 AND :D2
	INTO :TOTALCOMPRA;
	
	FOR SELECT DISTINCT S.IDP, S.NOMEPROD 
	FROM SP_BUSCA_PROD(:D1, :D2) S
	ORDER BY S.NOMEPROD
	INTO :IDPROD, :NOMEPRODUTO
	DO BEGIN
		SELECT SUM(IV.QUANTIDADE * IV.VALORUNITARIO)
		FROM ITEMVENDA IV
		INNER JOIN VENDA V ON IV.CODVENDA = V.CODIGO
		WHERE V.DATAVENDA BETWEEN :D1 AND :D2 AND IV.CODPRODUTO = :IDPROD
		INTO :VALORVENDA;
		
		SELECT SUM(IC.QUANTIDADE * IC.VALORUNITARIO)
		FROM ITEMCOMPRA IC
		INNER JOIN COMPRA C ON IC.CODCOMPRA = C.CODIGO 
		WHERE C.DATACOMPRA BETWEEN :D1 AND :D2 AND IC.CODPRODUTO = :IDPROD
		INTO :VALORCOMPRA;
		
		PERCVENDA = (:VALORVENDA * 100) / :TOTALVENDA;
		PERCCOMPRA = (:VALORCOMPRA * 100 ) / :TOTALCOMPRA;
		SUSPEND;
	END
END 

-- media apos entre 4ms e 5ms