--View com total de Vendas por Cliente


CREATE VIEW V_SUMTVENDAS (cLIENTE, TOTALVENDAS)AS
SELECT C.NOME, SUM(V.TOTAL)
FROM VENDA V
JOIN CLIENTE C ON V.CODCLIENTE = C.CODIGO
WHERE EXTRACT(YEAR FROM V.DATAVENDA) = 2017
GROUP BY C.NOME

SELECT * FROM V_SUMTVENDAS

-- 2 - Que mostre os 5 produtos mais vendidos no mês de agosto/2017. Agrupar pelo nome do produto.

CREATE VIEW V_PRODMAISVENDIDOS_2017 (Produto, TotalDeVendas) AS
SELECT FIRST 5 P.NOME, SUM(IT.QUANTIDADE)
FROM ITEMVENDA IT
JOIN PRODUTO P ON IT.CODPRODUTO = P.CODIGO
JOIN VENDA V ON IT.CODVENDA = V.CODIGO
WHERE EXTRACT (YEAR FROM V.DATAVENDA)=2017 AND EXTRACT(MONTH FROM V.DATAVENDA)=08
GROUP BY P.NOME
ORDER BY 2 DESC 

DROP VIEW V_PRODMAISVENDIDOS_2017

SELECT * FROM V_PRODMAISVENDIDOS_2017;

--Fazer Stored Procedure:

--3 - Que implemente o exercício 1, com passagem de parâmetros referente ao período.

CREATE PROCEDURE SP_TOTALVENDAS(ANO D_INTEIRO)
RETURNS (CLIENTE D_STR060,TVENDAS D_DECIMAL)
AS 
BEGIN
	FOR SELECT C.NOME, SUM(V.TOTAL)
		FROM VENDA V
		JOIN CLIENTE C ON V.CODCLIENTE = C.CODIGO
		WHERE EXTRACT(YEAR FROM V.DATAVENDA)=:ANO
		GROUP BY C.NOME
		INTO :CLIENTE, :TVENDAS
	DO BEGIN
		SUSPEND;			
	END 
END			


SELECT V.CLIENTE, V.TVENDAS
FROM SP_TOTALVENDAS(2017) V;
-- 4 - Que implemente o exercício 2, com passagem de parâmetros referente ao período.

CREATE PROCEDURE SP_PRODMAISVENDIDOS(ANO D_INTEIRO, MES D_INTEIRO)
RETURNS (PRODUTO D_NOME, TVENDAS D_DECIMAL)
AS 
BEGIN
	FOR SELECT FIRST 5 P.NOME, SUM(V.TOTAL)
		FROM ITEMVENDA IT
		JOIN PRODUTO P ON IT.CODPRODUTO = P.CODIGO
		JOIN VENDA V ON IT.CODVENDA = V.CODIGO		
		WHERE EXTRACT(YEAR FROM V.DATAVENDA)=:ANO AND EXTRACT(MONTH FROM V.DATAVENDA)=:MES
		GROUP BY P.NOME
		ORDER BY 2 DESC
		INTO :PRODUTO, :TVENDAS
	DO BEGIN
		SUSPEND;			
	END 
END			


SELECT * FROM ITEMVENDA;

SELECT * FROM VENDA

SELECT V.PRODUTO, V.TVENDAS
FROM SP_PRODMAISVENDIDOS (2017,8) V;


